// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-sjGhg-IyvHcDVQW14tC60Q2LghQNOvo',
    appId: '1:105090792290:web:bc7b91650f124b71608a3b',
    messagingSenderId: '105090792290',
    projectId: 'goride-c9c3e',
    authDomain: 'goride-c9c3e.firebaseapp.com',
    storageBucket: 'goride-c9c3e.firebasestorage.app',
    measurementId: 'G-GWK4CRE4BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFdG1Z41K29jCn_WXG6peZtULS1bwAc9Q',
    appId: '1:105090792290:android:77b2d3312a862552608a3b',
    messagingSenderId: '105090792290',
    projectId: 'goride-c9c3e',
    storageBucket: 'goride-c9c3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9b2BGy78RxNPRRSatMuJhDQbrUNCkmi8',
    appId: '1:105090792290:ios:d2f0cc3acffc4ade608a3b',
    messagingSenderId: '105090792290',
    projectId: 'goride-c9c3e',
    storageBucket: 'goride-c9c3e.firebasestorage.app',
    iosBundleId: 'com.example.hailingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9b2BGy78RxNPRRSatMuJhDQbrUNCkmi8',
    appId: '1:105090792290:ios:d2f0cc3acffc4ade608a3b',
    messagingSenderId: '105090792290',
    projectId: 'goride-c9c3e',
    storageBucket: 'goride-c9c3e.firebasestorage.app',
    iosBundleId: 'com.example.hailingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-sjGhg-IyvHcDVQW14tC60Q2LghQNOvo',
    appId: '1:105090792290:web:d7177a090a127ea8608a3b',
    messagingSenderId: '105090792290',
    projectId: 'goride-c9c3e',
    authDomain: 'goride-c9c3e.firebaseapp.com',
    storageBucket: 'goride-c9c3e.firebasestorage.app',
    measurementId: 'G-7TRSJ9FJWT',
  );
}
